POST http://localhost:8080/api/v1/goals
Content-Type: application/json

{
  "title": "스프링 부트 연결 성공!",
  "description": "H2 DB 연결 기념 목표 생성 테스트",
  "targetDate": "2025-11-23"
}

### 2. 목표 수정하기 (Update)
PUT http://localhost:8080/api/v1/goals/1
Content-Type: application/json

{
  "title": "목표 수정 성공!",
  "description": "제목이랑 내용이 아주 잘 바뀌었습니다.",
  "targetDate": "2025-12-25"
}

###

DELETE http://localhost:8080/api/v1/goals/1